### ISSUE TITLE
ゲームオーバー

### ISSUE THREAD

**Issue by c0a21022** [C0A21006/ProjExD#13]
https://github.com/C0A21006/ProjExD/blob/132c69fd4628fe27ba8d74aa52991a6d6fdbebdf/ex04/dodge_bomb.py#L70

root=tk.Tk()
root.withdraw()
の2文を入れた上でメッセージボックスを使えばゲームオーバーのウィンドウの実装ができると思います。

**Comment by C0A21006** [comment]
あとで頑張ってみます
